# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: Africa/Cairo

# jekyll-seo-tag settings
title: Abdelrahman Ghoneim
tagline: GIS Developer & Full-Stack Engineer
description: >-
  GIS Developer, Full-Stack Engineer, and Data Science enthusiast.
  Specialized in spatial analytics, web applications, and intelligent systems.

# Fill in the protocol & hostname for your site
url: "https://ghonim0007.github.io"

# The base URL of your site
baseurl: "/abdelrahmanghoneim.github.io"

github:
  username: ghonim0007

twitter:
  username: yourusername

social:
  name: Abdelrahman Ghoneim
  email: your.email@example.com
  links:
    - https://github.com/ghonim0007
    - https://linkedin.com/in/abdelrahmanghoneim

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# Web Analytics Settings
analytics:
  google:
    id: # ضع هنا G-XXXXXXXXXX من Google Analytics
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics ID

# Prefer color scheme setting.
theme_mode: # [light | dark]

# The CDN endpoint for media resources.
cdn:

# the avatar on sidebar, support local or CORS resources
avatar: /assets/images/profile.jpg

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: giscus # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with your Disqus shortname
  # utterances settings
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options
  giscus:
    repo: ghonim0007/abdelrahmanghoneim.github.io
    repo_id: R_kgDOQMcvLg
    category: Announcements
    category_id: DIC_kwDOQMcvLs4CxRmp
    mapping: pathname
    strict: 0
    input_position: bottom
    lang: en
    reactions_enabled: 1

# Self-hosted static assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    env: # [development | production]

pwa:
  enabled: true # the option for PWA feature (installable)
  cache:
    enabled: true # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
